# Generated by Django 5.1.6 on 2025-03-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0002_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
            ],
        ),
    ]
